name: Publish to NPM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Publish next version
        run: |
          VERSION="0.1.0-next.$(date +%Y%m%d%H%M%S)"
          npm version $VERSION --no-git-tag-version
          npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
